### ISSUE TITLE
error while compileing using  catkin_make

### ISSUE THREAD

**Issue by ghost** [VisualComputingInstitute/BiternionNets-ROS#2]
hello,
i hope you are doing fine ,i'm a student at the university i doing my master's thesis about classification using service robots and i'm trying to develop a  new way to classify people like age,gender,how many people are in the group ...etc
so i found a good project named spencerProject then i tried to give it a try and i found that its using an asus camera not like me i have a kinect difference between the drivers openni and openni2 so i tried a lot to make work i finally did but i found that the topic "/spencer/sensors/rgbd_front_top" is the responible for that then i was searching on how to replace it so i across y'r project on github and i found that u haven't change it u just add some detaills to it so i download u'r project and when i tries to make it with catkin_make it's giving me an error thats why i sending this email to ask you to help me i'm stucked i mean my project is not doing the compatibility asus xtion--->microsoftKinect so please reply to me soon as possible i really need that and thank you forgiving time to read this.

**Comment by ghost** [comment]
this is the error message : 
Using these message generators: gencpp;genlisp;genpy
CMake Error at /opt/ros/indigo/share/catkin/cmake/catkinConfig.cmake:75 (find_package):
  Could not find a package configuration file provided by
  "rwth_pedestrian_tracking" with any of the following names:

```
rwth_pedestrian_trackingConfig.cmake
rwth_pedestrian_tracking-config.cmake
```

  Add the installation prefix of "rwth_pedestrian_tracking" to
  CMAKE_PREFIX_PATH or set "rwth_pedestrian_tracking_DIR" to a directory
  containing one of the above files.  If "rwth_pedestrian_tracking" provides
  a separate development package or SDK, be sure it has been installed.
Call Stack (most recent call first):
  BiternionNets-ROS-master/CMakeLists.txt:7 (find_package)

-- Configuring incomplete, errors occurred!
See also "/home/elbarko/BI_project/build/CMakeFiles/CMakeOutput.log".
See also "/home/elbarko/BI_project/build/CMakeFiles/CMakeError.log".
make: **\* [cmake_check_build_system] Error 1
Invoking "make cmake_check_build_system" failed

**Comment by lucasb-eyer** [comment]
As the message says, you don't have the `rwth_pedestrian_tracking` package. You can find it over here: https://github.com/spencer-project/spencer_people_tracking

**Comment by ghost** [comment]
thank you so mutch  but there are no such file or dir please can you help
me find it i'm new to ROS so i'm learning by time

2016-02-28 23:09 GMT+01:00 Lucas Beyer notifications@github.com:

**Comment by lucasb-eyer** [comment]
If you're new to ROS, please do yourself the favor and go through their excellent tutorials and documentation.

To use the package, you need to clone the repository into your ROS workspace's `src` folder.

**Comment by hacker-boy** [comment]
yes i did that by saying new i mean this is my first time working with ros and i finished the tutorials

**Comment by ghost** [comment]
thanks now it telling me that libnite2 not found

**Comment by ghost** [comment]
[rospack] Error: package 'libnite2' not found

**Comment by ghost** [comment]
many thanks for helping me i did what y've told to do but now i'm getting
this type of error :
[rospack] Error: package 'libnite2' not found
NiTE_DIR = /common/lib/NiTE2/
LINK_NAME = /home/elbarko/.ros/NiTE2
Link /home/elbarko/.ros/NiTE2 to /common/lib/NiTE2/ already exists.
[100%] Built target cob_body_tracker
/home/elbarko/BI_project/src/BiternionNets-ROS-master/src/dump_tracks.cpp:19:52:
fatal error: spencer_tracking_msgs/TrackedPersons2d.h: No such file or
directory
 #include <spencer_tracking_msgs/TrackedPersons2d.h>
                                                    ^
compilation terminated.
make[2]: ***
[BiternionNets-ROS-master/CMakeFiles/dump_tracks.dir/src/dump_tracks.cpp.o]
Error 1
make[1]: **\* [BiternionNets-ROS-master/CMakeFiles/dump_tracks.dir/all]
Error 2
make: **\* [all] Error 2

## Invoking "make -j4 -l4" failed

i know that there are no trackedperson2d.msg thats why ther are no file
generated .h so the question is is it ok if i make som modifying to the
spencer project
and thank you for all what u are doing to me u'r awesome

**Comment by lucasb-eyer** [comment]
I believe both of these errors are unrelated to `BiternionNets-ROS`. They are problems with setting up other packages (namely, NiTE2 and `spencer_people_tracking`).

If it is the case that `BiternionNets-ROS` is not compatible with the current version of `spencer_people_tracking`, I will notice and fix that in mid-March. I don't have the time right now, sorry!

**Comment by ghost** [comment]
thank you thats all what i needed i mean it has to be an error right thank you for what you are doing and please if you did any thing new let me know i will be glad
